### ISSUE TITLE
Name of Wifi doesn't appear. There is no Mobile Data toggle.

### ISSUE THREAD

**Issue by NieR-R** [rostopira/wifi_qs#12]
As title says. Can you please add a toggle for the Mobile Data as well ?
If possible the wifi name as well, though not a priority. 
Thanks a lot anyway!!
Edit: Also the toggle doesn't work when fly mod is one.

**Comment by fillwithjoy1** [comment]
I don't think this project is ever going to be updated, however you need to grant the location permission to the app for the SSID to appear

**Comment by NieR-R** [comment]
Shame. I can live with all those "bugs" except for the toggle in the airplane mode. :/

**Comment by fillwithjoy1** [comment]
> Shame. I can live with all those "bugs" except for the toggle in the airplane mode. :/

So I have actually found a better alternative app called "[Better Internet Tiles](https://play.google.com/store/apps/details?id=be.casperverswijvelt.unifiedinternetqs)" in the play store.
You'll need Shizuku, but after that you're all good

**Comment by NieR-R** [comment]
I tried it, but wasn't able to get it to work even after activating Shizuku.

    On Tuesday, December 13, 2022 at 01:16:21 PM GMT+1, Joy ***@***.***> wrote:  
 
 



Shame. I can live with all those "bugs" except for the toggle in the airplane mode. :/


So I have actually found a better alternative app called "Better Internet Toggles" in the play store.
You'll need Shizuku, but after that you're all good

**Comment by rostopira** [comment]
In v1.1 I've added activity that asks for location permission to fix that
