### ISSUE TITLE
XDA Fix Defunct, this is now the only way to restore a wifi toggle

### ISSUE THREAD

**Issue by thanhtacles** [rostopira/wifi_qs#15]
So successive messages on that same XDA thread have concluded that the ADB commands no longer work; Google has stripped this in the latest build and patched it. As of then, this is the only fix that still works and doesn't require some complicated background process override. The only issue is that it'll say "Disconnected" instead of the wifi network name. If that was fixed, then this becomes the best workaround.

**Comment by rostopira** [comment]
From readme:

> Location permission is optional, if you want to show connected Wi-Fi SSID and currently must be granted manually.

Grant location permission, and it will show you Wi-Fi name
