### ISSUE TITLE
where is apk for 1.1 release?

### ISSUE THREAD

**Issue by Skrell** [rostopira/wifi_qs#16]
Love this app btw!  Just installed 1.0 on my new Pixel 6a and works great!

**Comment by blackmoth1911** [comment]
Please upload the apk for 1.1

**Comment by OldBuffGuy** [comment]
+1

**Comment by rostopira** [comment]
Yeah, I thought it was successfully built using github actions, but it wasn't.
I've no idea, what's wrong with my setup.
Built on my machine and attached APK into releases tab.

**Comment by rostopira** [comment]
https://github.com/rostopira/wifi_qs/releases/download/latest/app-release.apk

**Comment by Skrell** [comment]
Thank you this is an essential app for me!

**Comment by Skrell** [comment]
Is there anything you can do about the constant "disconnected" status displayed?  Maybe at least give an option to hide it completely if it can't be accurate?

**Comment by rostopira** [comment]
@Skrell you need to give app location permission, otherwise SSID of the WiFi can't be retreived
