### ISSUE TITLE
F-Droid release?

### ISSUE THREAD

**Issue by VictorVow** [rostopira/wifi_qs#3]
It would be great to be able to get this app via F-Droid.

**Comment by rostopira** [comment]
I've looked into F-Droid release process, and that seems too complicated.
But as I understood, anyone can do that instead of me.
I will leave this issue open, if anyone wants to contribute.

**Comment by rostopira** [comment]
This repo is done, there is an easier way now: https://www.xda-developers.com/bring-back-wifi-mobile-data-quick-settings-tiles-android-12-adb/
