### ISSUE TITLE
QS Tile Always Says "Disconnected"

### ISSUE THREAD

**Issue by adamperez** [rostopira/wifi_qs#5]
Just installed the latest build and the tile always says "Disconnected", even when I on/off cycle using the QS toggle.

Pixel 6 Pro
Android 12 (SD1A.210817.036.A8)

**Comment by mayghalV** [comment]
I have the same issue on Pixel 3a

**Comment by rostopira** [comment]
I can't reproduce on Pixel 4, for some reason. Could you try to grant location permission? You have to do it manually via settings

**Comment by rostopira** [comment]
BTW, just to clarify, "Disconnected" means that Wi-Fi is on, but not connected to any network

**Comment by ghoff** [comment]
I would have reported the same error.  Both Pixel 6 and 3 running Android 12 showed Disconnected.  I granted location permission to both phones and now both show the network they are connected to.  

I read the readme but somehow misunderstood the comment about location access.

**Comment by rostopira** [comment]
This repo is done, there is an easier way now: https://www.xda-developers.com/bring-back-wifi-mobile-data-quick-settings-tiles-android-12-adb/

**Comment by anuajay01** [comment]
How to uninstall this?

**Comment by ArnavD74** [comment]
> How to uninstall this?

search for the app in the apps section in setting, and uninstall it from there

**Comment by alikve** [comment]
> This repo is done, there is an easier way now: https://www.xda-developers.com/bring-back-wifi-mobile-data-quick-settings-tiles-android-12-adb/

The adb-commands doesn't work on android 13, this app works (at least on pixel 4a).

**Comment by fillwithjoy1** [comment]
> > This repo is done, there is an easier way now: https://www.xda-developers.com/bring-back-wifi-mobile-data-quick-settings-tiles-android-12-adb/
> 
> The adb-commands doesn't work on android 13, this app works (at least on pixel 4a).

The internet tile got reworked [Source](https://www.reddit.com/r/Android/comments/x0sv6u/wifi_and_mobile_data_toggles_in_android_13_a/). Use ['Better Internet Tiles'](https://play.google.com/store/apps/details?id=be.casperverswijvelt.unifiedinternetqs)

**Comment by rostopira** [comment]
In v1.1 I've added activity that asks for location permission to fix that
