### ISSUE TITLE
Google Pixel 6 Pro - commands don't work

### ISSUE THREAD

**Issue by SciLor** [rostopira/wifi_qs#7]
The commands won't work on my Google Pixel 6 Pro with Android 12. It just moves the cell toggle to the front
```
settings put global settings_provider_model false
settings put secure sysui_qs_tiles "wifi,cell,$(settings get secure sysui_qs_tiles)"
```

settings get secure sysui_qs_tiles shows that the Wi-Fi was added but not visible.

**Comment by rostopira** [comment]
Unfortunately, I don't have a Pixel 6 to test, only Pixel 5 and 2

**Comment by ArnavD74** [comment]
I just used the released apk on my Pixel 6 Pro (Android 13) and works perfectly. I don't know about the adb, but this is a good workaround. Just give it location permission for the SSID preview.

**Comment by retorquere** [comment]
The ADB commands do not stick on my pixel 5. Please do not deprecate this APK, we need this :(

**Comment by fillwithjoy1** [comment]
Just hoping if we can ever get a mobile data quick toggle -_-

**Comment by fillwithjoy1** [comment]
A13 commands don't work as the code for the internet quick settings tile has been reworked [Source](https://www.reddit.com/r/Android/comments/x0sv6u/wifi_and_mobile_data_toggles_in_android_13_a/)
However I'd recommend [Better Internet Tiles](https://play.google.com/store/apps/details?id=be.casperverswijvelt.unifiedinternetqs) as it also offers the ability to toggle mobile data and nfc as well. You'll just need Shizuku
