### ISSUE TITLE
This app help me a lot in Android 13

### ISSUE THREAD

**Issue by zyh941** [rostopira/wifi_qs#8]
Hello, I know it is a good way to separate wifi and mobile data tiles in quick settings panel via adb execution, but it does not work in stock Android 13. I heard from other developer that there is almost no possibility to bring back wifi and mobile data tiles again. I tried wifi_qs, and fortunately it worked. So you can stop deprecated this app. Thanks for your effort, if it is possible to bring mobile data tile in Android 13, it will be better!

**Comment by Tyerlo** [comment]
Can confirm that on Pixel 5 running on android 13 the app still works to have a separate wifi toggle. But as @zyh941 mentioned it would nice to have mobile data_qs as well.

**Comment by atleasta** [comment]
The wifi toggle appears in the menu but without function. When I tap on it, I can't activate/deactivate wifi. I've got a Pixel 5, too with Android 13. Do I have to consider something? 
Thanks in advance!

**Comment by zyh941** [comment]
> The wifi toggle appears in the menu but without function. When I tap on it, I can't activate/deactivate wifi. I've got a Pixel 5, too with Android 13. Do I have to consider something? Thanks in advance!

Please stop asking me in my issue. If you have any issue, please start a new issue and ask the author of module for help.
